// Code generated by "stringer -type=Command"; DO NOT EDIT.

package notions

import "fmt"

const _Command_name = "DoNotionCreateDoNotionDeleteDoNotionAppendDoNotionTruncateDoItemCreateDoItemDeleteDoItemAppendDoItemTruncateDoItemInsertDoItemChildDoItemPruneDoTextInsertDoTextDeleteDoTextAppendDoTextTruncateDoStyleTagDoStyleDelDoSessionItemAppendDoSessionItemTruncate"

var _Command_index = [...]uint8{0, 14, 28, 42, 58, 70, 82, 94, 108, 120, 131, 142, 154, 166, 178, 192, 202, 212, 231, 252}

func (i Command) String() string {
	i -= 1
	if i < 0 || i >= Command(len(_Command_index)-1) {
		return fmt.Sprintf("Command(%d)", i+1)
	}
	return _Command_name[_Command_index[i]:_Command_index[i+1]]
}
